feat: add customisation option for document classification
louh/control-records pull request #15
Opened 2022-08-26 01:42 UTC by elliotwutingfeng

Classification footer can be changed to anything other than "Confidential" (limited to 15 characters or less), like "Top Secret", "Restricted" etc.

Reset to Default button is also provided.

2022-08-31 01:07 UTC, louh requested changes
Hi @elliotwutingfeng, thank you for your contribution! I'm happy to take this. Just a couple minor changes: one bug fix (including a fix for an existing bug that you have uncovered, thank you), and a style change. If you're able to update your PR I will approve and merge. Thanks!

2022-08-31 01:07 UTC, louh commented on src/components/ContentEditor.vue
> +          localStorage.setItem(FBC_CLASSIFICATION, this.classification)
There seems to be a bug where this doesn't get saved properly, and neither does the `recno`. Setting the item to `this.editedClassification` and `this.editedRecno` (fixing the previous line) should make this work.

2022-08-31 01:07 UTC, louh commented on src/components/ContentEditor.vue
> +}
We also need a margin between the classification input line and the record number line above. A value of `1em` should be fine.

2022-08-31 02:07 UTC, elliotwutingfeng commented on src/components/ContentEditor.vue
> +          localStorage.setItem(FBC_CLASSIFICATION, this.classification)
Fixed!

2022-08-31 02:07 UTC, elliotwutingfeng commented on src/components/ContentEditor.vue
> +}
Fixed!

2022-09-02 18:38 UTC, louh commented
Look great. Thanks for the addition, @elliotwutingfeng!

2022-09-02 18:38 UTC, louh approved these changes

2022-09-02 18:38 UTC, merged